### ISSUE TITLE
[Question] You are aware that F3+F4 exists, right?

### ISSUE THREAD

**Issue by Qendolin** [AmyMialeeMods/creative-keybind#1]
Not to be rude but...

**Comment by PseudoDistant** [comment]
It didn't before either 1.15 or 1.16 (I forgor), time for me to do le epic backport.

**Comment by AmyMialee** [comment]
Yea, also this was made cause I was using command blocks and it was annoying doing f3+f4, one key was just what i needed so i made it public.

**Comment by PseudoDistant** [comment]
> Yea, also this was made cause I was using command blocks and it was annoying doing f3+f4, one key was just what i needed so i made it public.

This is a good reason, I tend to just make a macro tho lol
